{
 "title": "Loki",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id!=\"\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INFO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({level=\"INFO\"} [$__auto])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "WARN",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({level=\"WARN\"} [$__auto])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "ERROR",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({level=\"ERROR\"} [$__auto])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "INFO Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{level=\"INFO\"} |= ``"
    }
   ]
  },
  {
   "title": "WARN Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "{level=\"WARN\"} |= ``"
    }
   ]
  },
  {
   "title": "ERROR Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "{level=\"ERROR\"} |= ``"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "count_over_time({level=\"INFO\"} [$__auto])",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "count_over_time({level=\"WARN\"} [$__auto])",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "count_over_time({level=\"ERROR\"} [$__auto])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({level=\"INFO\"} |= `` [$__auto])",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "count_over_time({level=\"WARN\"} |= `` [$__auto])",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "count_over_time({level=\"ERROR\"} |= `` [$__auto])",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}